/*
 * Copyright (C) 2020 Acme Technologies, Inc.  All rights reserved.
 */
/**
 * All the feature flags in saas-mfe-config-hub module.
 */
export enum FeatureFlags {
	// TODO: Remove in https://acme.atlassian.net/browse/PLTIN-4106
	PLT_UI_ADMIRAL_CONFIG_HUB_DRAFT_DETAILS = 'PLT_UI_ADMIRAL_CONFIG_HUB_DRAFT_DETAILS',
	// TODO: Remove in https://acme.atlassian.net/browse/PLTCONFHUB-1336
	PLT_UI_ADMIRAL_CONFIG_HUB_JSON_CHANGELOG = 'PLT_UI_ADMIRAL_CONFIG_HUB_JSON_CHANGELOG',
	// Todo: Clean up in https://acme.atlassian.net/browse/PLTIN-3647
	PLT_UI_ADMIRAL_TENANT_CONNECTIONS = 'PLT_UI_ADMIRAL_TENANT_CONNECTIONS',
	// TODO: Clean up in https://acme.atlassian.net/browse/PLTCONFHUB-1026
	PLT_UI_ADMIRAL_TENANT_CONNECTIONS_NAV = 'PLT_UI_ADMIRAL_TENANT_CONNECTIONS_NAV',
	// TODO: Cleanup in https://acme.atlassian.net/browse/PLTCONFHUB-1039.
	PLT_UI_ADMIRAL_CONFIG_HUB_OBJECT_OPTIONS_DROPDOWN = 'PLT_UI_ADMIRAL_CONFIG_HUB_OBJECT_OPTIONS_DROPDOWN',
	PLT_UI_ADMIRAL_CONFIG_HUB_OBJECT_MAPPING = 'PLT_UI_ADMIRAL_CONFIG_HUB_OBJECT_MAPPING',
	PLT_UI_ADMIRAL_CONFIG_HUB_BACKUP_DETAILS = 'PLT_UI_ADMIRAL_CONFIG_HUB_BACKUP_DETAILS',
	// Clean up https://acme.atlassian.net/browse/PLTCONFHUB-1473
	PLTCONFHUB_JSON_DIFF_VIEW = 'PLTCONFHUB_JSON_DIFF_VIEW',
	// TODO: Clean up in https://acme.atlassian.net/browse/PLTCONFHUB-1545
	PLT_UI_ADMIRAL_CONFIG_HUB_METADATA_OVERLAY = 'PLT_UI_ADMIRAL_CONFIG_HUB_METADATA_OVERLAY',
	// Clean Up during https://acme.atlassian.net/browse/PLTCONFHUB-1786
	PLT_UI_ADMIRAL_CONFIG_HUB_BACKUP_UPLOAD = 'PLT_UI_ADMIRAL_CONFIG_HUB_BACKUP_UPLOAD',
	// Feature flag to enable sp config approvals
	PLT_UI_ADMIRAL_CONFIG_HUB_DRAFTS_APPROVAL = 'PLT_UI_ADMIRAL_CONFIG_HUB_DRAFTS_APPROVAL',
	PLTIN_CONFIG_HUB_LIMIT_OVERRIDE = 'PLTIN_CONFIG_HUB_LIMIT_OVERRIDE',
	// Feature flag that enables a new field "Fyle sync info"
	PLTCONFHUB_2666_UPDATE_FILE_SYNC_INFO = 'PLTCONFHUB_2666_UPDATE_FILE_SYNC_INFO',
	PLTCONFHUB_SCHEDULED_ACTIONS = 'PLTCONFHUB_SCHEDULED_ACTIONS'
}
