/*
 * Copyright (C) 2024 Acme Technologies, Inc.  All rights reserved.
 */
import { Component, ElementRef, EventEmitter, Input, OnInit, Output, input, signal } from '@angular/core';

import { Observable } from 'rxjs';

import { FeatureFlagService } from '@acme-priv/ui-common/src/acme/angular/util';

import { FeatureFlags } from '../../../feature-flags.enum';
import { HarborPilotStore } from 'app/harbor-pilot/harbor-pilot.store';
import {
	HarborPilotCommandActionDef,
	HarborPilotMessage,
	HarborPilotMessageFeedback,
	HarborPilotNavigationActionDef,
	MessageSentimentType,
	MessageType,
	SentimentIconTypes
} from 'app/harbor-pilot/shared/models/messages.model';

@Component({
	selector: 'app-harbor-pilot-chat-message',
	templateUrl: './harbor-pilot-chat-message.component.html',
	styleUrls: ['./harbor-pilot-chat-message.component.scss']
})
export class HarborPilotChatMessageComponent implements OnInit {
	// eslint-disable-next-line @angular-eslint/no-input-rename
	@Input({ required: true }) message: HarborPilotMessage;

	/**
	 * The navigation action to be rendered as a message
	 */
	@Input() navigationAction: HarborPilotNavigationActionDef;

	/**
	 * The command action to be rendered as a message
	 */
	@Input() commandAction: HarborPilotCommandActionDef;

	/**
	 * The aligment of the message, can be 'center'. Default is 'unset'.
	 */
	alignment = input('unset');

	/**
	 * Turns the background color of the message full white.
	 */
	@Input() isWhiteBackground = false;

	/**
	 * Output that emits an event containing the rating given to the bot message
	 */
	@Output() userFeedbackSubmitted = new EventEmitter<HarborPilotMessageFeedback>();

	/**
	 * Output that emits an event containing the action
	 */
	@Output() onActionClick = new EventEmitter();

	/**
	 * Rating given by the user to the bot message
	 */
	public feedback: HarborPilotMessageFeedback;

	/**
	 * Feature Flag for whether the debugger IDs should be displayed or not
	 * Cleanup FF https://acme.atlassian.net/browse/UIDATA-1117
	 */
	public isDebuggerEnabled: boolean;

	/**
	 * Whether to show the quick start tiles
	 */
	public isUserFeedbackOverlayOpen = signal(false);

	/**
	 * The icon type for sentiment to be used by the template
	 */
	public sentimentIconTypes = SentimentIconTypes;

	/**
	 * Enum collection of message types.
	 */
	public messageTypes = MessageType;

	/**
	 * Enum collection of message sentiments types, represents an
	 * up or down vote for how usefull are our AI generated responses.
	 */
	public messageSentimentType = MessageSentimentType;

	/**
	 * The last message generated by the BOT.
	 */
	public lastBotMessage$: Observable<HarborPilotMessage>;

	constructor(
		private featureFlagService: FeatureFlagService,
		private harborPilotStore: HarborPilotStore,
		public elementRef: ElementRef
	) {}

	/**
	 * On Initialization lifecycle method
	 */
	ngOnInit() {
		// Cleanup FF https://acme.atlassian.net/browse/UIDATA-1117
		this.isDebuggerEnabled = this.featureFlagService.isEnabled(FeatureFlags.UIDATA1115_HARBOR_PILOT_DEBUGGER);
		// Get the last bot message from the state.
		this.lastBotMessage$ = this.harborPilotStore.selectLastBotMessage$;
	}

	/**
	 * Handles clicks on the rating buttons
	 * @param {MessageSentimentType} sentiment - The sentiment that was clicked
	 */
	handleRating(sentiment: MessageSentimentType): void {
		// Show an extensive user feedback form to be filled before storing the rate.
		if (sentiment === MessageSentimentType.DOWN) {
			this.isUserFeedbackOverlayOpen.set(true);
		} else {
			this.feedback = { sentiment };
			this.userFeedbackSubmitted.emit({ sentiment });
		}
	}

	/**
	 * Handles the click on the action
	 * @param action - The action that was clicked
	 */
	handleActionClick(action): void {
		this.onActionClick.emit(action);
	}

	/**
	 * Handles user feedback form submit event.
	 * @param feedback: HarborPilotMessageFeedback
	 */
	onUserFeedbackFormSubmit(feedback: HarborPilotMessageFeedback) {
		this.feedback = feedback;
		this.isUserFeedbackOverlayOpen.set(false);
		this.userFeedbackSubmitted.emit(feedback);
	}

	/**
	 * Handles user feedback form cancel event.
	 */
	onUserFeedbackFormCancel() {
		this.isUserFeedbackOverlayOpen.set(false);
	}
}
